In [16]:
import pandas as pd
pd.set_option('display.max_columns', None)
import numpy as np
np.set_printoptions(threshold=np.inf)
#nc.sort_values('Apprehension Date',ascending=True).head()

In [56]:
#In the months after the Border Patrol’s high-profile raid ended in Charlotte, 
#ICE has quietly arrested a record high number of people statewide: about 2,300.
#A little less than half of those arrested have left the country already, mainly to Mexico, Honduras and Guatemala
nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
nc = nc[nc['Apprehension Date']>'2025-11-19']

print(gb.arrests.sum())

print(nc.shape)

gb = nc.groupby('Case Status').size().to_frame(name='arrests').reset_index()
print(464+99+100+381)
print(1044/2295)

left_country = ['3-Voluntary Departure Confirmed,'
               '6-Deported/Removed - Deportability',
               '8-Excluded/Deported/Removed',
               '8-Excluded/Removed - Inadmissibility']
left = nc[nc['Case Status'].isin(left_country)]
print(left['Departure Country'].value_counts())


gb.head(10)

2295
(2308, 42)
1044
0.4549019607843137
Departure Country
MEXICO                199
HONDURAS              130
GUATEMALA              61
EL SALVADOR            44
VENEZUELA              13
NICARAGUA              11
COLOMBIA                7
ECUADOR                 5
PERU                    4
BRAZIL                  2
DOMINICAN REPUBLIC      2
HAITI                   1
COSTA RICA              1
SENEGAL                 1
Name: count, dtype: int64

                            Case Status  arrests
0       3-Voluntary Departure Confirmed      464
1    6-Deported/Removed - Deportability       99
2           8-Excluded/Deported/Removed      100
3  8-Excluded/Removed - Inadmissibility      381
4                                ACTIVE     1209
5                      B-Relief Granted        1
6   E-Charging Document Canceled by ICE       41

In [ ]:
#They didn’t break for the holidays. 
#ICE arrested 10 people on Thanksgiving, 14 people on Christmas Eve and Christmas, and 19 on New Year’s Eve and Day.
nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
xmas = nc[(nc['xmaseve'] == 'yes') | (nc['xmas'] == 'yes')]
thx = nc[nc['thx']=='yes']
ny = nc[(nc['nye'] == 'yes') | (nc['nyd'] == 'yes')]
print(xmas.shape)
print(thx.shape)
print(ny.shape)
holidays = pd.concat([xmas, thx, ny])

#A Venezuelan man in his 50s arrested on Christmas Eve had no criminal charges or convictions. 
#The same goes for a Honduran man in his 30s arrested on New Year’s Eve.print(2026-1970)
print(2026-1994)
print(2026-1970)
holidays[holidays['Apprehension Criminality']=='3 Other Immigration Violator']

In [67]:
#The ramp up brings the number of people ICE has arrested in North Carolina to nearly 6,500 since President Donald Trump took office, through early March.
#They arrested double the number of people from January 20 through early March of this year, compared to the same time frame last year.

nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
nc = nc[nc['Apprehension Date']>='2025-01-20']
gb = nc.groupby('comparetime').size().to_frame(name='arrests').reset_index()
print(gb.arrests.sum())
print(1077/512)
gb.head()

6469
2.103515625

            comparetime  arrests
0             last_year      512
1  not in compare range     4880
2             this_year     1077

In [63]:
#ICE simultaneously arrested about 270 people statewide during those five days. 
#Most were men from Central America and, on average, in their early 30s.
#During Charlotte’s Web, more than half of the people arrested — 147 — did not have charges or convictions.
#About 60 others had pending charges, but federal data do not disclose what most of their charges are. 
nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
nc = nc[nc['Apprehension Date']>='2025-01-20']
nc = nc[nc['clt_web']=='yes']
gb = nc.groupby('Apprehension Criminality').size().to_frame(name='arrests').reset_index()
print('Total arrests during CW: ', gb.arrests.sum())
gb['perc'] = gb['arrests']/(gb['arrests'].sum())
print(nc['Citizenship Country'].value_counts())
print('Average birth year of people arrested during CW: ', nc['Birth Year'].mean())
print(nc['Gender'].value_counts())
gb.head()

Total arrests during CW:  269
Citizenship Country
MEXICO                100
HONDURAS               56
GUATEMALA              47
EL SALVADOR            18
VENEZUELA              13
ECUADOR                 7
COLOMBIA                6
NICARAGUA               5
PERU                    3
CUBA                    3
HAITI                   2
DOMINICAN REPUBLIC      2
TURKIYE                 1
NEPAL                   1
VIETNAM                 1
SYRIA                   1
BELIZE                  1
INDIA                   1
GEORGIA                 1
Name: count, dtype: int64
Average birth year of people arrested during CW:  1987.1635687732341
Gender
Male       252
Female      16
Unknown      1
Name: count, dtype: int64

       Apprehension Criminality  arrests      perc
0          1 Convicted Criminal       65  0.241636
1    2 Pending Criminal Charges       57  0.211896
2  3 Other Immigration Violator      147  0.546468

In [ ]:
#Typically, people without criminal charges or convictions make up about one in five ICE arrests. 
nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
nc = nc[nc['Apprehension Date']>='2025-01-20']
gb = nc.groupby('Apprehension Criminality').size().to_frame(name='arrests').reset_index()
print(gb.arrests.sum())
gb['perc'] = gb['arrests']/(gb['arrests'].sum())
gb.head()

In [64]:
#More than three-quarters of everyone ICE arrested during those five days have already left the country, mostly voluntarily.
nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
nc = nc[nc['Apprehension Date']>='2025-01-20']
nc = nc[nc['clt_web']=='yes']
gb = nc.groupby('Case Status').size().to_frame(name='arrests').reset_index()
print(gb.arrests.sum())
print('Total arrested during CW who left: ', 114+18+3+76)
print('Percent of people during CW who have left:', 211/268)
gb.head(10)

268
Total arrested during CW who left:  211
Percent of people during CW who have left: 0.7873134328358209

                            Case Status  arrests
0       3-Voluntary Departure Confirmed      114
1    6-Deported/Removed - Deportability       18
2           8-Excluded/Deported/Removed        3
3  8-Excluded/Removed - Inadmissibility       76
4              A-Proceedings Terminated        2
5                                ACTIVE       51
6   E-Charging Document Canceled by ICE        4

In [48]:
#Figures show nearly half of all the people arrested this year were facing charges. 
#During the same time frame last year, less than a third of the people arrested had pending charges. 
nc = pd.read_csv('/Users/cmcglade/Documents/Projects/ice-update-april-2026/processed-data/nc-arrests-april-26-update.csv')
nc = nc[nc['Apprehension Date']>='2025-01-20']
gb = nc.groupby(['comparetime','Apprehension Criminality']).size().to_frame(name='arrests').reset_index()
gb['total_arrests'] = gb.groupby('comparetime')['arrests'].transform('sum')
gb['perc']=gb['arrests']/gb['total_arrests']
gb=gb[gb['comparetime']!='not in compare range']
gb.head(10)

  comparetime      Apprehension Criminality  arrests  total_arrests      perc
0   last_year          1 Convicted Criminal      267            512  0.521484
1   last_year    2 Pending Criminal Charges      160            512  0.312500
2   last_year  3 Other Immigration Violator       85            512  0.166016
6   this_year          1 Convicted Criminal      361           1077  0.335190
7   this_year    2 Pending Criminal Charges      527           1077  0.489322
8   this_year  3 Other Immigration Violator      189           1077  0.175487